# Génère lines.json : répertoire d'ouvertures validé par python-chess.
# Chaque ligne : san + commentaires ; le script vérifie la légalité de chaque coup,
# l'absence de prise en passant (non gérée par l'appli) et le mat annoncé.
import chess
import json

# (san, commentaire ou None) — les commentaires s'affichent dans l'appli.
LINES = [
    # ------------------------- BLANCS -------------------------
    dict(
        id="anglaise-chouchou", side="w", emoji="🦁",
        title="Ouverture à l'anglaise — spéciale CHOUCHOU LOUIS",
        desc="1.c4 ! Ton arme souple : tu contrôles d5, tu t'adaptes à l'adversaire et tu ne joues JAMAIS en pilote automatique.",
        story="L'Anglaise porte le nom de Howard Staunton, le plus fort joueur du monde vers 1843, qui l'employa dans son match-titre. C'est l'ouverture des stratèges : pas de bagarre immédiate, mais un étau qui se resserre. Carlsen et Kramnik l'adorent. La règle d'or : regarde ce que fait l'adversaire AVANT de jouer ton coup.",
        moves=[
            ("c4", "L'Anglaise ! Tu contrôles la case d5 et tu restes souple : aucun pion engagé au centre, tu t'adaptes à CE QU'IL JOUE. 🦁"),
            ("e5", None),
            ("Nc3", "Tu développes en luttant pour les cases d5 et e4. Dans l'Anglaise, toute la bataille tourne autour de d5."),
            ("Nf6", None),
            ("g3", "Le plan maître : ton fou ira en g2, roi de la grande diagonale (vers d5 et b7). C'est LA pièce de l'Anglaise."),
            ("d5", "⚠️ Coup à repérer absolument ! Il frappe ton centre. Ne joue pas la suite par réflexe : si tu le laisses pousser ...d4, ton cavalier est chassé et il prend tout l'espace. Il faut réagir MAINTENANT."),
            ("cxd5", "Prends ! Tu élimines son pion avant qu'il n'avance ...d4. Te développer sans prendre serait l'erreur classique.", {
                "Bg2": "Pilote automatique = danger ! Tu développes au lieu de réagir, et ...d4 ! chasse ton cavalier c3 : il prend l'espace. Le plus net est de PRENDRE : cxd5 !",
                "Nf3": "Attention : sans prendre, ...d4 chasse ton cavalier et te gêne. D'abord cxd5 !",
            }),
            ("Nxd5", None),
            ("Bg2", "Maintenant ton fou rayonne : il fixe le cavalier d5 et vise b7. Sens la pression sur la grande diagonale !"),
            ("Nb6", None),
            ("Nf3", "Développe et garde un œil sur e5. Tu n'as toujours créé aucune faiblesse : c'est toute la force de ton système."),
            ("Nc6", None),
            ("O-O", "Roi à l'abri AVANT de lancer quoi que ce soit. On n'attaque jamais le roi resté au centre."),
            ("Be7", None),
            ("d3", "Petit coup, grand sens : tu ouvres ton fou c1 et tu prépares e4 ou Fe3. Patience — tu agis quand TOI tu décides."),
            ("O-O", None),
            ("Be3", "Tout est connecté, zéro faiblesse ! Ton plan : viser la case d5 et son cavalier b6, ou pousser sur l'aile dame. Tu es légèrement mieux et tu joues sans risque. 🎯"),
        ],
        variations=[
            dict(at=3, name="Le dragon inversé (2...Cc6 et ...g6)", moves=[
                ("Nc6", None),
                ("g3", "Même plan : fianchetto. Il copie tes idées (le « dragon inversé ») — mais TOI tu as un temps de plus. Sers-t'en !"),
                ("g6", None),
                ("Bg2", "Ton fou prend sa diagonale."),
                ("Bg7", None),
                ("d3", "Solide. Et maintenant, un plan TRÈS concret se dessine : l'expansion à l'aile dame."),
                ("d6", None),
                ("Rb1", "« Une tour avant d'avoir roqué ?! » Oui, et c'est sans danger : le centre est verrouillé (les pions se bloquent), il n'a AUCUNE attaque rapide contre ton roi — tu roqueras tranquillement plus tard. Pour l'instant, le plus urgent c'est ton plan : Rb1 prépare b4-b5 pour bousculer son cavalier c6 et ouvrir l'aile dame, là où tu es le plus fort. Ce n'est pas machinal — c'est un PLAN."),
                ("a5", "Il joue ...a5 pour freiner ton b4. Logique — mais tu vas quand même y arriver."),
                ("a3", "Tu prépares b4 malgré ...a5 (b4 axb4 axb4 et la colonne a s'ouvre pour ta tour). Toute la partie se jouera à l'aile dame, à TON avantage. 🦁"),
            ]),
            dict(at=5, name="Le clouage 3...Fb4", moves=[
                ("Bb4", None),
                ("Bg2", "Il cloue ton cavalier c3 ? Reste calme : finis ton développement, ce clouage ne fait aucun mal."),
                ("O-O", None),
                ("e4", "Pourquoi e4 ici, alors que d'habitude tu joues le petit d3 ? Pour deux raisons ! 1) Son fou parti en b4 ne contrôle plus e4 : la case est libre, tu prends donc TOUT le centre d'un coup. 2) Ton fou g2 défend déjà e4 sur la grande diagonale — d'ailleurs si ...Cxe4 ?, alors Fxe4 ! et tu gagnes la pièce. S'il échange en c3, tu obtiens en plus la paire de fous, un atout qui dure."),
                ("Bxc3", None),
                ("bxc3", "Tu reprends vers le centre. Le marché : tu as des pions c doublés (le petit prix), mais en échange les DEUX fous et un beau centre c4-e4 (le gros lot). La paire de fous est un avantage qui dure. Développe, puis pousse au centre quand c'est mûr. 🐘"),
            ]),
            dict(at=1, name="La symétrique (1...c5)", moves=[
                ("c5", None),
                ("Nc3", "Il imite tous tes coups (la « symétrique »). Règle d'or : dans une position symétrique, celui qui CASSE la symétrie le premier, avec un temps d'avance, prend l'initiative. Ce sera toi."),
                ("Nc6", None),
                ("g3", "Fianchetto, comme toujours."),
                ("g6", None),
                ("Bg2", "Ton fou sur sa diagonale."),
                ("Bg7", None),
                ("Nf3", "Développe tranquillement."),
                ("Nf6", None),
                ("O-O", "Roi à l'abri."),
                ("O-O", None),
                ("d4", "LE coup ! Tu casses la symétrie au centre, avec ton temps d'avance. Voilà la différence entre copier bêtement et jouer activement."),
                ("cxd4", None),
                ("Nxd4", "Tu reprends au centre : plus d'espace, l'initiative, et aucune copie aveugle. Tu as frappé le premier. 🎯"),
            ]),
            dict(at=1, name="L'anglo-indienne (1...Cf6, il refuse ...e5)", moves=[
                ("Nf6", None),
                ("Nc3", "Il ne joue pas ...e5 : il prépare un fianchetto (la Roi-Indienne... à l'envers). Surtout, ne change rien : installe ton système habituel, tu as un temps d'avance sur lui."),
                ("g6", None),
                ("g3", "Ton fianchetto, comme toujours. Tu copies SES idées avec un temps de plus — exactement comme dans le dragon inversé."),
                ("Bg7", None),
                ("Bg2", "Ton fou sur sa grande diagonale."),
                ("O-O", None),
                ("Nf3", "Développe en gardant un œil sur e5, la case qu'il va vouloir prendre."),
                ("d6", None),
                ("O-O", "Roi à l'abri avant tout."),
                ("e5", "Le voilà, ...e5 : il occupe enfin le centre. On retombe sur une structure que tu connais, mais toujours avec ton temps d'avance."),
                ("d3", "Solide : tu ouvres ton fou c1 et tu prépares l'expansion à l'aile dame."),
                ("Nc6", None),
                ("Rb1", "La même clé que dans le dragon inversé : tu prépares b4-b5 pour bousculer son cavalier c6 et ouvrir l'aile dame. La grande leçon : même quand il refuse ...e5, tu retrouves TON plan — l'Anglaise s'adapte à tout. 🦁"),
            ]),
            dict(at=5, name="Le fou actif 3...Fc5", moves=[
                ("Bc5", None),
                ("Bg2", "Finis ton fianchetto, tranquille : son fou c5 lorgne f2, mais f2 n'est pas attaquable pour l'instant."),
                ("O-O", None),
                ("e3", "Le coup malin contre ...Fc5 : tu fermes la diagonale du fou (il ne mord plus sur f2 ni d4) ET tu prépares la poussée d4 qui le chassera."),
                ("Re8", None),
                ("Nge2", "Pourquoi Cge2 et pas Cf3 comme d'habitude ? Parce que de e2 ton cavalier ne bouche PAS ton pion d : tu gardes la poussée d4 ! disponible pour repousser le fou c5 et prendre le centre. Petit détail, grand sens."),
                ("d6", None),
                ("O-O", "Roi à l'abri. Ton plan est limpide : jouer d4 au bon moment pour gagner de l'espace et reléguer son fou c5. Tu es légèrement mieux, sans aucun risque. 🎯"),
            ]),
        ],
    ),
    dict(
        id="italienne-blancs", side="w", emoji="🏛️",
        title="L'Italienne tranquille",
        desc="Ton plan principal avec les Blancs : développement rapide, roque, puis attaque !",
        story="L'Italienne est l'une des plus vieilles ouvertures du monde : les maîtres italiens Polerio et Greco l'analysaient déjà vers 1600 ! Son petit nom, « Giuoco Piano », veut dire « jeu tranquille ». Et elle n'a pas pris une ride : Magnus Carlsen la joue encore au plus haut niveau.",
        moves=[
            ("e4", "Tu prends le centre et tu ouvres la voie à ton fou et à ta dame."),
            ("e5", None),
            ("Nf3", "Tu développes en attaquant le pion e5 : un coup, deux idées !", {
                "Qh5": "Le coup du berger ?! Tu sais toi-même le punir (c'est ton module ⚔️ !) : un adversaire préparé chasse ta dame en développant et tu te retrouves en retard partout. Cf3, propre et fort !",
            }),
            ("Nc6", None),
            ("Bc4", "Le fou vise f7, la case la plus fragile des Noirs."),
            ("Bc5", None),
            ("c3", "Tu prépares d4 pour construire un grand centre."),
            ("Nf6", None),
            ("d3", "Solide : tu protèges e4 et tu libères ton fou c1.", {
                "d4": "Trop pressé ! Après ...exd4 cxd4 vient ...Fb4+ ! l'échec qui dérange — exactement le coup que TOI tu joues avec les Noirs contre l'Italienne ! D'abord d3 et le roque, le centre viendra après.",
            }),
            ("d6", None),
            ("O-O", "Le roi à l'abri AVANT d'attaquer. Toujours !"),
            ("O-O", None),
            ("Re1", "La tour soutient le centre et prépare la suite."),
            ("a6", None),
            ("Bb3", "Tu mets ton fou à l'abri de ...Na5 : il reste braqué sur f7."),
            ("Ba7", None),
            ("h3", "Petit coup malin : tu interdis ...Bg4 qui clouerait ton cavalier."),
            ("h6", None),
            ("Nbd2", "Le plan magique : ce cavalier va voyager d2 → f1 → g3 vers le roi noir !"),
        ],
        variations=[
            dict(at=3, name="La Petroff (2...Cf6)",
                story="Nommée d'après Alexandre Petrov, le premier grand champion russe (vers 1840). Sa réputation : ultra-solide, presque ennuyeuse — les pros l'utilisent pour neutraliser 1.e4. D'où l'importance du petit piège De2 que tu apprends ici !",
                moves=[
                ("Nf6", None),
                ("Nxe5", "Prends ! Et retiens le piège : s'il copiait avec ...Cxe4 ?, De2 ! gagnerait une pièce (échec à la découverte en c6)."),
                ("d6", None),
                ("Nf3", "Recule tranquillement : il va reprendre e4, c'est prévu."),
                ("Nxe4", None),
                ("d4", "Le grand centre, comme toujours."),
                ("d5", None),
                ("Bd3", "Tu développes en visant son cavalier e4 : il devra le défendre encore et encore."),
                ("Nc6", None),
                ("O-O", "Roi à l'abri avant la suite."),
                ("Be7", None),
                ("c4", "Tu grignotes son centre : un peu plus d'espace pour toi, partie facile à jouer."),
            ]),
            dict(at=5, name="Le piège Blackburne-Shilling (3...Cd4 ?!)",
                story="Ce piège porte le nom de Joseph Blackburne, champion anglais des années 1880 surnommé « la Mort Noire ». La légende raconte qu'il le tendait dans les cafés de Londres pour gagner un shilling (une petite pièce) par partie ! Aujourd'hui encore, des joueurs malins le tentent en blitz et en tournois jeunes contre ceux qui gobent le pion e5. Toi, maintenant, tu sauras.",
                moves=[
                ("Nd4", None),
                ("Nxd4", "STOP, c'est un piège célèbre ! Son cavalier a l'AIR d'abandonner e5... Si tu gobais le pion : Cxe5 ?? Dg5 ! attaquerait ton cavalier ET g2 en même temps — et après Cxf7 Dxg2 Tf1 Dxe4+ Fe2... Cf3 ÉCHEC ET MAT ! Prends simplement son cavalier d4 : c'est LUI qui a gaffé."),
                ("exd4", None),
                ("c3", "Tu dissous son pion avancé tout en préparant ton développement."),
                ("dxc3", None),
                ("Nxc3", "Compte les pièces : tu développes en reprenant, lui n'a RIEN développé. Son piège est devenu ton avantage. 😎 La suite est limpide : joue vite et simple — d4 pour le grand centre, le roque, sors tes fous — et ton énorme avance de développement fera la différence toute seule."),
            ]),
            dict(at=5, name="Les Deux Cavaliers (3...Cf6)", moves=[
                ("Nf6", None),
                ("d3", "Contre les Deux Cavaliers, joue tranquille : d3 protège e4 avant tout."),
                ("Bc5", None),
                ("c3", "Comme dans la ligne principale : tu prépares d4."),
                ("d6", None),
                ("O-O", "Roi à l'abri, comme toujours."),
                ("O-O", None),
                ("Re1", "La tour soutient le centre : tu retrouves TA position habituelle !"),
                ("a6", None),
                ("Bb3", "Même maison, autre chemin : c'est la force d'un vrai répertoire. Et donc le MÊME plan que ta ligne principale : ton cavalier b1 partira en voyage d2 → f1 → g3, droit vers le roi noir ! 🏛️"),
            ]),
        ],
    ),
    dict(
        id="piege-legal", side="w", emoji="🪤",
        title="Le piège de Légal",
        desc="Un piège célèbre quand les Noirs jouent ...d6 et ...Bg4 : tu « sacrifies » ta dame... pour faire mat !",
        story="M. de Kermeur, sire de Légal, était le plus fort joueur de France vers 1750 et le professeur du grand Philidor, au célèbre café de la Régence à Paris. Sa partie contre Saint Brie (1750) — celle que tu apprends ! — est l'une des miniatures les plus fameuses de l'histoire des échecs.",
        moves=[
            ("e4", "Le centre, comme toujours."),
            ("e5", None),
            ("Nf3", "Développement avec attaque sur e5."),
            ("Nc6", None),
            ("Bc4", "Le fou vise f7."),
            ("d6", None),
            ("Nc3", "Tu développes tranquillement... le piège se prépare."),
            ("Bg4", None),
            ("h3", "Tu poses la question au fou : il doit choisir. (S'il lâche le clouage par ...Fxf3, reprends simplement Dxf3 : pas de piège aujourd'hui, mais tu gardes la paire de fous et une position agréable.)"),
            ("Bh5", None),
            ("Nxe5", "Le coup de tonnerre ! Oui, ta dame est en prise... mais regarde la suite ! (Et s'il ne gobe pas la dame, ...Cxe5, alors Dxh5 ! et tu ressors avec un pion de plus : le piège paie quand même.)"),
            ("Bxd1", None),
            ("Bxf7+", "Échec ! Le roi noir est obligé d'avancer."),
            ("Ke7", None),
            ("Nd5#", "ÉCHEC ET MAT avec deux cavaliers et un fou ! La dame n'a même pas servi. 🎉"),
        ],
    ),
    dict(
        id="fried-liver", side="w", emoji="🍳",
        title="La Fried Liver (contre 3...Cf6)",
        desc="L'arme fatale contre les Deux Cavaliers : le sacrifice Cxf7 ! qui arrache le roi noir de sa maison. Alternative musclée à ton tranquille 4.d3.",
        story="Ce sacrifice est étudié depuis plus de 400 ans : l'Italien Polerio le notait déjà vers 1610 ! Son drôle de nom vient de l'italien « fegatello », le foie frit... car le roi noir se fait cuire à petit feu au milieu de l'échiquier. C'est l'une des attaques les plus redoutées des tournois jeunes du monde entier.",
        moves=[
            ("e4", "Comme toujours."),
            ("e5", None),
            ("Nf3", "Développement avec attaque sur e5."),
            ("Nc6", None),
            ("Bc4", "Le fou vise f7."),
            ("Nf6", None),
            ("Ng5", "L'attaque ! Deux pièces visent f7 : la menace Cxf7 est immédiate.", {
                "d3": "Très bon coup aussi... mais c'est ta ligne TRANQUILLE (variante Deux Cavaliers de l'Italienne) ! Ici on dégaine l'arme musclée : Cg5 ! et f7 tremble.",
            }),
            ("d5", None),
            ("exd5", "Prends : il doit maintenant décider comment récupérer d5..."),
            ("Nxd5", None),
            ("Nxf7", "LE SACRIFICE du Foie Frit ! Tu donnes un cavalier pour arracher le roi noir au grand jour.", {
                "Bxd5": "Ne reprends pas le pion : après ...Dxd5 ! sa dame se centralise en attaquant ton cavalier g5 ET g2. Le grand moment, c'est le sacrifice Cxf7 !",
            }),
            ("Kxf7", None),
            ("Qf3+", "Échec ! Le roi est obligé d'avancer en e6 pour sauver son cavalier d5 cloué.", {
                "Qh5+": "Mauvais échec : ...g6 ! repousse ta dame et il se consolide. Df3+ ! est LA pointe : il cloue le cavalier d5 et force le roi à s'avancer.",
            }),
            ("Ke6", None),
            ("Nc3", "Encore une pièce sur d5 : tout ton monde converge vers le roi baladeur."),
            ("Nb4", None),
            ("O-O", "Roque ! Son roi à lui erre en plein centre (e6), alors tu mets le tien à l'abri — et ta tour file vers les colonnes centrales. Et si son cavalier gobe c2 (...Cxc2) ? Laisse-le ! Fxd5+ ! et son roi est traqué : dans la Fried Liver, le roi compte, pas les pions. Prochaine étape : ouvrir le jeu avec d4, pile sur son roi."),
            ("c6", None),
            ("d4", "Ouvre le centre tout de suite : avec un roi en e6, chaque colonne ouverte est un danger mortel. À toi de conclure ! 🔥"),
        ],
        variations=[
            dict(at=9, name="La bonne défense 5...Ca5",
                story="...Ca5 ! était déjà recommandé par Polerio en... 1610 ! C'est la seule vraie parade au Foie Frit — et 400 ans plus tard, les théoriciens se disputent ENCORE pour savoir qui est mieux. Toi, tu joues simple : un pion de plus et une bonne position.",
                moves=[
                ("Na5", None),
                ("Bb5+", "Il connaît la parade ! Pas grave : échec intermédiaire, tu gardes l'initiative."),
                ("c6", None),
                ("dxc6", "Prends encore : ton pion d5 se transforme en pion c6."),
                ("bxc6", None),
                ("Be2", "Recule au calme : tu as UN PION DE PLUS et une position saine. Il va attaquer pour compenser : défends, échange les pièces, et ta technique fera le reste. 🧮"),
            ]),
        ],
    ),
    dict(
        id="anti-sicilienne", side="w", emoji="🛡️",
        title="Contre la Sicilienne : l'Alapin",
        desc="Si on te joue 1...c5, réponds 2.c3 : tu construis ton grand centre quand même !",
        story="Elle porte le nom de Semion Alapin, maître russe né en 1856. Longtemps regardée de haut (« trop sage ! »), elle a pris sa revanche : les champions modernes l'utilisent pour éviter la jungle des Siciliennes et imposer LEUR plan. Exactement ton idée !",
        moves=[
            ("e4", "Ton premier coup, toujours le même."),
            ("c5", None),
            ("c3", "L'idée : préparer d4 et reprendre du pion c. Le grand centre arrive.", {
                "d4": "Bon coup... mais c'est ton MORRA ! 💣 Ici on s'entraîne à l'Alapin : c3 prépare le même grand centre, sans sacrifier de pion.",
            }),
            ("Nf6", None),
            ("e5", "Tu chasses le cavalier en gagnant de l'espace."),
            ("Nd5", None),
            ("d4", "Voilà ton grand centre ! C'est tout l'intérêt de 2.c3."),
            ("cxd4", None),
            ("Nf3", "Développe d'abord, reprends après : pas de précipitation.", {
                "Qxd4": "Ta dame au milieu trop tôt : ...e6 puis ...Cc6 la chasseraient en développant gratuitement. Cf3 d'abord — le pion ne s'envolera pas.",
            }),
            ("Nc6", None),
            ("cxd4", "Tu reprends : deux pions au centre contre zéro, l'espace est pour toi."),
            ("d6", None),
            ("Bc4", "Le fou attaque le cavalier d5 qui n'a plus de bonne case."),
            ("Nb6", None),
            ("Bb5", "Tu cloues le cavalier c6 (il ne peut plus bouger, son roi est juste derrière). Bilan de l'Alapin : DEUX pions au centre contre zéro, plus d'espace, et toutes tes pièces sortent facilement — pendant que lui doit défendre son pion d6 et son centre. Prochaine étape : roque, Cc3, et tu pousses ton avantage tranquillement. Pas de feu d'artifice, juste une position où tu es mieux partout. 🛡️"),
        ],
        variations=[
            dict(at=3, name="La riposte 2...d5", moves=[
                ("d5", None),
                ("exd5", "Prends : sa dame va devoir venir au milieu trop tôt."),
                ("Qxd5", None),
                ("d4", "Ton grand centre arrive quand même : c'est tout le plan de 2.c3."),
                ("Nf6", None),
                ("Nf3", "Développement naturel."),
                ("e6", None),
                ("Be2", "Tranquille : le roque approche."),
                ("Nc6", None),
                ("O-O", "Roi en sécurité."),
                ("cxd4", None),
                ("cxd4", "Tu reprends : beau centre, jeu facile."),
                ("Be7", None),
                ("Nc3", "Développe EN attaquant sa dame : un temps gratuit ! Elle doit fuir, et pendant ce temps toi tu déploies tout (Fg5, Te1) avec plus d'espace et un jeu facile. C'est tout l'esprit de l'Alapin : un petit avantage tranquille, sans jamais rien risquer. 🛡️"),
            ]),
        ],
    ),
    dict(
        id="morra", side="w", emoji="💣",
        title="Le gambit Smith-Morra (anti-Sicilienne)",
        desc="Ton arme surprise contre 1...c5 : un pion sacrifié contre un développement éclair et des pièges partout !",
        story="Nommé d'après le Français Pierre Morra, puis popularisé par le Texan Ken Smith. Anecdote : au grand tournoi de San Antonio 1972, Smith l'a tenté contre trois grands maîtres... et a perdu les trois parties ! Mais en parties jeunes et rapides, c'est une machine à pièges terriblement efficace.",
        moves=[
            ("e4", "On commence pareil."),
            ("c5", None),
            ("d4", "Tu offres un pion tout de suite : c'est le Morra ! En échange, un développement foudroyant."),
            ("cxd4", None),
            ("c3", "Le deuxième coup du gambit : s'il prend, toutes tes pièces vont sortir avec des menaces.", {
                "Qxd4": "Surtout pas : ...Cc6 ! chasserait ta dame en développant — tu offrirais le temps que ton gambit veut justement gagner. Le Morra, c'est c3 !",
            }),
            ("dxc3", None),
            ("Nxc3", "Un pion de moins, mais regarde : cavalier dehors, et les colonnes c et d s'ouvrent pour tes tours."),
            ("Nc6", None),
            ("Nf3", "Pièce après pièce, sans reprendre ton souffle."),
            ("d6", None),
            ("Bc4", "Le fou vise f7, comme d'habitude."),
            ("e6", None),
            ("O-O", "Roi à l'abri : tu es déjà prêt, lui non."),
            ("Nf6", None),
            ("Qe2", "Le secret du Morra : la dame en e2 laisse la colonne d à la tour..."),
            ("Be7", None),
            ("Rd1", "...et voilà ! Ta tour fixe sa dame aux rayons X sur la colonne d : son pion d6 est dans le collimateur. Le plan pour enfoncer le clou : Ff4 et Cb5 viennent tous deux sur d6, pendant que ton fou c4 guette f7 et e6. Le pion sacrifié est le prix ; cette avalanche de pièces actives est le gain. S'il relâche une seconde, d6 ou f7 craque — c'est ça, un gambit. ⚡"),
        ],
        variations=[
            dict(at=11, name="Le piège 6...Cf6 ? 7.e5 !", moves=[
                ("Nf6", None),
                ("e5", "Le coup de tonnerre du Morra ! Tout s'ouvre d'un coup sur le cavalier f6 et le pion d6."),
                ("dxe5", None),
                ("Qxd8+", "Échange d'abord les dames..."),
                ("Nxd8", None),
                ("Nb5", "...et voilà la pointe : Cc7+ menace, fourchette royale sur le roi et la tour !"),
                ("Rb8", None),
                ("Nxe5", "Pion récupéré, et regarde f7 et c7 trembler sous tes deux cavaliers et ton fou : position de rêve. 🌪️"),
            ]),
            dict(at=5, name="Le refus 3...Cf6", moves=[
                ("Nf6", None),
                ("e5", "Il refuse le gambit ? Chasse le cavalier en gagnant de l'espace."),
                ("Nd5", None),
                ("Nf3", "Développe tranquillement..."),
                ("Nc6", None),
                ("cxd4", "...reprends ton pion..."),
                ("d6", None),
                ("Bc4", "...attaque le cavalier d5..."),
                ("Nb6", None),
                ("Bb5", "...et te voilà EXACTEMENT dans ton Alapin ! Deux ouvertures pour le prix d'une. 😄"),
            ]),
        ],
    ),
    dict(
        id="anti-francaise", side="w", emoji="🥖",
        title="Contre la Française : l'avance",
        desc="Si on te joue 1...e6, pousse e5 : tu gagnes de l'espace et le fou c8 reste enfermé !",
        story="La variante d'avance était l'arme favorite d'Aaron Nimzowitsch, le grand penseur des années 1920. Sa théorie : une chaîne de pions e5-d4 bien défendue « étrangle » lentement l'adversaire. Tu joues donc comme un philosophe des échecs !",
        moves=[
            ("e4", "On commence pareil."),
            ("e6", None),
            ("d4", "Deux pions au centre, profites-en."),
            ("d5", None),
            ("e5", "Tu avances ! Le fou c8 des Noirs est enfermé derrière ses pions."),
            ("c5", None),
            ("c3", "Tu défends d4 : ta chaîne de pions est solide comme un mur.", {
                "dxc5": "Ne gobe pas c5 : tu abandonnerais ton beau centre, et son fou reprend le pion en développant — tu connais la leçon, c'est le piège de la Londres à l'envers ! Soutiens d4 avec c3.",
            }),
            ("Nc6", None),
            ("Nf3", "Développement en protégeant d4 une deuxième fois."),
            ("Qb6", None),
            ("a3", "Sa dame en b6 attaque ton pion b2 — mais regarde bien : b2 est gardé par ton fou c1 ! Donc ...Dxb2 ?? perdrait la dame sur-le-champ (Fxb2 !). Tu peux donc ignorer la « menace » et jouer pour TON plan : a3 prépare b4 (espace à l'aile dame) et enlève la case b4 à ses pièces."),
            ("Nh6", None),
            ("b4", "De l'espace à gauche aussi ! Ton centre tient, tu joues sur tout l'échiquier."),
        ],
    ),
    dict(
        id="anti-caro", side="w", emoji="🏰",
        title="Contre la Caro-Kann : l'avance",
        desc="Si on te joue 1...c6, même recette : pousse e5 et joue simple et solide.",
        story="La Caro-Kann porte les noms de deux amis, Horatio Caro et Marcus Kann, qui l'ont analysée en 1886. Et ta réponse 3.e5 a un parrain de luxe : le magicien Mikhaïl Tal l'a dégainée en match de championnat du monde contre Botvinnik en 1961 !",
        moves=[
            ("e4", "Toujours le même premier coup : c'est ça, un répertoire."),
            ("c6", None),
            ("d4", "Le grand centre, sans hésiter."),
            ("d5", None),
            ("e5", "Tu pousses et tu prends de l'espace pour de bon. ⚠️ Une différence avec la Française : ici son fou c8 n'est PAS enfermé, il va sortir librement en f5. Pas grave ! Ton plan ne dépend pas de ça : ton pion e5 lui mange tout l'air, et c'est cet espace qui va l'étouffer lentement."),
            ("Bf5", None),
            ("Nf3", "Développe et protège d4. Rien de spectaculaire — et c'est normal : contre la Caro, on ne gagne pas par un piège, mais par l'espace qui pèse coup après coup. Sois patient."),
            ("e6", None),
            ("Be2", "Fou modeste, mais malin : il ne s'engage à rien et prépare juste le roque. Quand c'est TOI qui as l'espace, pas besoin de fou agressif — tu gardes tes pièces souples et tu laisses l'adversaire à l'étroit."),
            ("Nd7", None),
            ("O-O", "Roi à l'abri. Tu as l'espace ET tout ton temps : c'est LUI qui est serré, pas toi. Aucune raison de te presser."),
            ("Ne7", None),
            ("Nbd2", "Et voilà le plan promis ! 🎯 Ce cavalier file vers b3, puis vise la case c5 : un trou magnifique en plein camp noir, où il sera impossible à déloger. Ton idée pour toute la partie : manœuvrer tranquillement (Cb3, et parfois la poussée c4 contre son pion d5) pendant que les Noirs, tout tassés derrière e6 et d5, n'ont pas d'air pour respirer. Tu gagnes par étouffement, pas par K.-O. 🐍"),
        ],
    ),
    dict(
        id="anti-scandinave", side="w", emoji="🛶",
        title="Contre la Scandinave",
        desc="1...d5 : très joué chez les jeunes ! Prends, puis harcèle sa dame sortie trop tôt.",
        story="Record du monde d'ancienneté : la plus vieille partie d'échecs modernes jamais notée (Valence, vers 1475 !) commençait par 1.e4 d5. Et la Scandinave mord encore : le Danois Bent Larsen a battu le champion du monde Karpov avec, en 1979 !",
        moves=[
            ("e4", "Toujours pareil."),
            ("d5", None),
            ("exd5", "Prends sans hésiter : sa dame va devoir se montrer beaucoup trop tôt."),
            ("Qxd5", None),
            ("Nc3", "Développe EN attaquant la dame : un temps gratuit pour toi !"),
            ("Qa5", None),
            ("d4", "Le grand centre, pendant que sa dame se promène."),
            ("Nf6", None),
            ("Nf3", "Développement simple : pièce après pièce."),
            ("c6", None),
            ("Bc4", "Le fou vise f7, comme d'habitude."),
            ("Bf5", None),
            ("Bd2", "Coup pro : tu protèges c3 et tu prépares une menace cachée (Cd5 !) et le grand roque."),
            ("e6", None),
            ("Qe2", "Avant-dernière étape : la dame libère d1 pour le grand roque. « Mais ça laisse c2 en prise ! » Pas de panique, c'est un pion empoisonné : si ...Fxc2 ?, tu joues d5 ! et le centre explose sur son roi resté coincé au milieu, pendant que sa dame se promène en a5. Tu gagnes bien plus qu'un pion."),
            ("Bb4", None),
            ("O-O-O", "Grand roque ! Pourquoi pas le petit ? Parce que ta tour atterrit PILE sur d1, la colonne du combat : elle soutient d4 et prépare la percée d4-d5. Et comme leur roi roquera petit, tu lanceras g4 ! (chasse le fou) puis g5 (chasse le cavalier) : une attaque gratuite, loin de ton roi bien gardé derrière a2-b2-c2. 💥"),
        ],
        variations=[
            dict(at=3, name="La moderne 2...Cf6", moves=[
                ("Nf6", None),
                ("d4", "Ne t'accroche pas au pion d5 : prends le centre ! Il reprendra son pion, toi tu développes."),
                ("Nxd5", None),
                ("Nf3", "Développement tranquille : tu as le centre, lui non."),
                ("g6", None),
                ("Be2", "Simple : le roque arrive."),
                ("Bg7", None),
                ("O-O", "Roi à l'abri."),
                ("O-O", None),
                ("c4", "Tu gagnes de l'espace en chassant son cavalier."),
                ("Nb6", None),
                ("Nc3", "Regarde ton centre et compare : l'espace est pour toi, partout. 🏰"),
            ]),
            dict(at=5, name="La retraite 3...Dd8", moves=[
                ("Qd8", None),
                ("d4", "Elle rentre à la maison ? Parfait : il a perdu deux temps, prends le centre."),
                ("Nf6", None),
                ("Nf3", "Développe, simplement : chaque coup compte."),
                ("Bg4", None),
                ("Be2", "Pare le clouage sans te presser."),
                ("e6", None),
                ("O-O", "Roi en sécurité : tu as le centre ET de l'avance au développement."),
                ("Be7", None),
                ("h3", "Pose la question au fou : s'il prend, Fxf3 visera b7. Le plan d'ensemble ? Tu as le centre ET un coup d'avance — sa dame est rentrée à la maison en perdant DEUX temps. Termine ton développement (Ff4 ou Fg5, puis Te1) et fais parler ton espace : il est tout serré, tu joues sur du velours. 🏰"),
            ]),
        ],
    ),
    dict(
        id="anti-pirc", side="w", emoji="🐉",
        title="Contre la Pirc (1...d6 et ...g6)",
        desc="Il te laisse tout le centre pour attaquer ton mur plus tard ? Installe-toi solidement, développe tout, et il ne se passera rien pour lui.",
        story="Nommée d'après Vasja Pirc, maître slovène. Son idée a fait scandale dans les années 1940 : laisser exprès le centre à l'adversaire pour le grignoter ensuite ! Une stratégie « hypermoderne »... qui ne marche que si les Blancs paniquent. Toi, tu ne paniques pas.",
        moves=[
            ("e4", "On commence pareil."),
            ("d6", None),
            ("d4", "Il te laisse le centre ? Prends-le en entier, merci !"),
            ("Nf6", None),
            ("Nc3", "Tu protèges e4 en développant."),
            ("g6", None),
            ("Nf3", "La Pirc ! Pas besoin de se précipiter : développe tout, ton centre est déjà gagné."),
            ("Bg7", None),
            ("Be2", "Simple et solide : le roque approche."),
            ("O-O", None),
            ("O-O", "Roi à l'abri. Ton centre est un mur, le sien n'existe pas."),
            ("Bg4", None),
            ("Be3", "Tu renforces d4 : son fou g7 mord dans la pierre."),
            ("Nc6", None),
            ("Qd2", "Tout est connecté ! Plan : h3 pour chasser le fou, puis avancer au centre quand TU le décides. 🗿"),
        ],
    ),
    # ------------------------- NOIRS -------------------------
    dict(
        id="anti-berger", side="b", emoji="⚔️",
        title="Stopper le coup du berger",
        desc="2.Dh5 ?! Beaucoup d'enfants le jouent. Apprends à punir la sortie de dame trop tôt !",
        story="En anglais on l'appelle « Scholar's mate », le mat de l'écolier — il piège des débutants depuis des siècles dans tous les cafés du monde. Chaque futur champion suit le même chemin : le découvrir, le subir UNE fois... puis le punir pour toujours. Tu en es à l'étape 3 !",
        moves=[
            ("e4", None),
            ("e5", "Tu prends ta part du centre."),
            ("Qh5", None),
            ("Nc6", "Surtout pas panique : tu défends e5 EN DÉVELOPPANT. Jamais ...g6 tout de suite ici.", {
                "g6": "...g6 ?? tout de suite perd une TOUR : Dxe5+ ! fourchette sur ton roi et ta tour h8 ! D'abord ...Cc6 pour protéger e5, le g6 viendra après.",
                "Nf6": "...Cf6 ?? ne protège pas e5 : Dxe5+ ! gobe ton pion central avec échec. Défends e5 d'abord : ...Cc6 !",
            }),
            ("Bc4", None),
            ("g6", "Maintenant oui : tu chasses la dame en préparant la maison du fou g7.", {
                "Nf6": "STOP ! ...Cf6 ?? laisse Dxf7 ÉCHEC ET MAT — le mat du berger, le vrai ! Chasse d'abord la dame avec ...g6, le cavalier viendra juste après.",
            }),
            ("Qf3", None),
            ("Nf6", "Elle revise f7 ? Tu défends f7 EN DÉVELOPPANT encore. Tu gagnes du temps à chaque coup."),
            ("Ne2", None),
            ("Bg7", "Le fou est superbe sur la grande diagonale."),
            ("Nbc3", None),
            ("d6", "Tu solidifies e5 (un 2e défenseur en plus du cavalier c6) et tu ouvres la porte à ton fou c8. Tu pourrais aussi roquer tout de suite, c'est tout aussi bon — ça revient exactement au même (tu joueras ...d6 juste après). Mais comme aucune menace ne pèse encore sur ton roi, autant faire d'abord le coup qui travaille, et roquer ensuite."),
            ("d3", None),
            ("O-O", "Roi à l'abri. Compte les pièces développées : toi 3 + roque, eux... une dame qui a perdu son temps ! 🎯"),
            ("O-O", None),
            ("Nd4", "Le saut royal ! Tu attaques sa dame pour la TROISIÈME fois — et ton cavalier lorgne aussi c2. Elle n'a jamais eu une seconde de repos."),
            ("Nxd4", None),
            ("exd4", "Reprends tranquillement : ton pion d4 chasse son cavalier c3 — encore un temps gagné ! Son attaque éclair s'est transformée en leçon de développement. 🎓 Et maintenant ? La position est saine et équilibrée — pas mal du tout contre quelqu'un qui voulait te mater en 4 coups ! Il cherchera la case forte d5 pour son cavalier : chasse-le calmement avec ...c6 le moment venu, sors tes dernières pièces (...Fe6, ...Cd7) et joue une partie tout ce qu'il y a de normal. Tu as déjà gagné la bataille du bon sens."),
        ],
        variations=[
            dict(at=4, name="Dame en f3 (3.Df3)", moves=[
                ("Qf3", None),
                ("Nf6", "Elle vise encore f7 ? Ton cavalier bloque le chemin EN se développant."),
                ("Bc4", None),
                ("g6", "Tu prépares la maison du fou : f7 est gardé par ton roi et bloqué par Cf6."),
                ("Ne2", None),
                ("Bg7", "Le fou rayonne sur la grande diagonale."),
                ("Nbc3", None),
                ("d6", "Tu solidifies e5 et libères ton fou c8."),
                ("d3", None),
                ("O-O", "Même punition que dans la ligne principale : tu es développé, sa dame a perdu son temps !"),
                ("O-O", None),
                ("Nd4", "Le saut royal, comme dans la ligne principale : ton cavalier attaque sa dame ENCORE une fois, et il lorgne c2 aussi !"),
                ("Nxd4", None),
                ("exd4", "Reprends : ton pion d4 chasse son cavalier c3 — encore un temps gagné ! 🎓 La suite : la position est équilibrée et facile à jouer pour toi. Il posera sûrement son cavalier sur la case forte d5 ; chasse-le posément (...c6), termine ton développement (...Fe6, ...Cd7) et joue tranquille. Le coup du berger est bel et bien mort et enterré."),
            ]),
        ],
    ),
    dict(
        id="italienne-noirs", side="b", emoji="🎯",
        title="Contrer l'Italienne",
        desc="Face à 3.Fc4 : développe ...Fc5, puis frappe au centre avec ...d5 — qu'il joue vif (c3-d4, Evans) ou tout calme (d3).",
        story="La riposte ...Fc5 est recommandée depuis le maître italien Greco, vers 1620. Et ton échec intermédiaire ...Fb4+ suivi de ...d5 est la recette d'égalisation que les champions appliquent depuis quatre siècles. Du solide, testé par le temps !",
        moves=[
            ("e4", None),
            ("e5", "Le centre, symétrique et solide."),
            ("Nf3", None),
            ("Nc6", "Tu défends e5 en développant."),
            ("Bc4", None),
            ("Bc5", "Ton fou prend la même belle diagonale que le sien."),
            ("c3", None),
            ("Nf6", "Tu contre-attaques e4 : pas le temps pour lui de tout faire."),
            ("d4", None),
            ("exd4", "Il pousse ? Tu prends. Ne laisse jamais un grand centre gratuit."),
            ("cxd4", None),
            ("Bb4+", "Échec intermédiaire ! C'est LE coup à connaître : tu gagnes un temps précieux."),
            ("Bd2", None),
            ("Bxd2+", "Tu échanges et il doit reprendre : encore un temps pour toi."),
            ("Nbxd2", None),
            ("d5", "Le coup libérateur ! Tu frappes le centre blanc avant qu'il s'installe."),
            ("exd5", None),
            ("Nxd5", "Égalité parfaite : ton cavalier d5 trône au centre — et ce n'est pas qu'un beau cavalier, c'est un BLOCUS idéal devant son pion d4, resté isolé (plus aucun pion ami pour le défendre). Ton plan pour la suite : roque, sors ton fou (...Fe6 ou ...Fg4), occupe les colonnes d et e... et ce pion d4 isolé deviendra ta cible pour toute la partie. 💪"),
        ],
        variations=[
            dict(at=6, name="L'Italienne tranquille (4.d3)",
                story="On l'appelle « Giuoco Pianissimo » : le jeu TRÈS tranquille. C'est l'arme moderne préférée de Magnus Carlsen face à l'Italienne : pas de bagarre, il veut t'étouffer lentement. Ta réponse : un plan clair et tu n'as rien à craindre.",
                moves=[
                ("d3", None),
                ("Nf6", "Il joue tout doux : aucun pion lancé, il veut juste t'enserrer petit à petit. Toi, développe normalement et garde un œil sur son pion e4."),
                ("c3", None),
                ("d6", "Tu copies son plan : ...d6 solidifie ton pion e5 et ouvre la sortie de ton fou c8.", {
                    "d5": "Trop tôt ! Après exd5 Cxd5, ton pion e5 reste sans défense et tombe : tu offres un pion pour rien. Garde la poussée ...d5 pour plus tard — d'abord ...d6 bien solide.",
                }),
                ("O-O", None),
                ("O-O", "Les deux rois sont à l'abri. Ce sera une partie de manœuvre : pas de K.-O., c'est le meilleur PLAN qui gagnera. Suis le tien."),
                ("Nbd2", None),
                ("a6", "Un coup malin qui empêche les bêtises : tu interdis les cases b5 à ses pièces ET tu prépares ...Fa7 pour ranger ton fou à l'abri."),
                ("Bb3", None),
                ("Ba7", "LE coup clé ! 🔑 Ton fou reste sur sa belle diagonale (il vise toujours f2) mais se planque en a7 : comme ça, si plus tard il joue d4 ou b4, ton fou ne sera pas chassé en perdant un temps. Un fou rangé d'avance, c'est un fou heureux."),
                ("h3", None),
                ("Be6", "Tu proposes d'échanger les fous de cases blanches. Son fou b3 est sa pièce la plus dangereuse — il braque f7 et toute ton aile roi. Pas de fou, pas d'attaque !"),
                ("Re1", None),
                ("Bxb3", "Échange fait : son meilleur attaquant quitte l'échiquier."),
                ("Qxb3", None),
                ("Qd7", "Position égale et parfaitement saine : son attaque est neutralisée. Ton plan tranquille : amène tes tours au centre (...Tae8, ...Tfd8) et prépare la libération ...d5 quand tout sera prêt. Patience, zéro risque — c'est une partie de manœuvre, et tu la joues bien. ✨"),
            ]),
            dict(at=6, name="Les Quatre Cavaliers (4.Cc3)",
                story="Quand les quatre cavaliers sortent et que tout est symétrique, beaucoup de joueurs ne savent plus quoi faire. Toi, tu sauras : reste simple, copie-le, et garde une longueur d'avance dans les idées.",
                moves=[
                ("Nc3", None),
                ("Nf6", "Les Quatre Cavaliers : la position est totalement symétrique. Pas de stress — développe et copie-le, comme un miroir."),
                ("d3", None),
                ("d6", "...d6 tient ton pion e5 et libère ton fou c8. Tu garderas la poussée ...d5 pour plus tard, quand tes pièces seront prêtes."),
                ("O-O", None),
                ("O-O", "Roi à l'abri. Bilan : position miroir, parfaitement égale et sans danger. Ton plan : développe ton fou (...Fe6 ou ...Fg4), occupe le centre avec tes tours, et prépare ...d5. Lui n'a aucune attaque — tu joues sans le moindre risque. 🪞"),
            ]),
            dict(at=6, name="Le cadeau 4.Cg5 ?? ",
                story="Le coup Cg5 vise f7, la case fragile : c'est l'idée du fameux « Fried Liver ». Sauf qu'ici, avec ton fou déjà sorti en c5, ce coup est une GROSSE gaffe. À toi de la punir !",
                moves=[
                ("Ng5", None),
                ("Qxg5", "Cadeau ! 🎁 Il joue Cg5 par réflexe pour attaquer f7... mais ton fou est en c5, plus en f8 : il ne bloque plus ta dame ! Alors ...Dxg5 et tu rafles le cavalier GRATUITEMENT — une pièce d'avance dès le 4e coup."),
                ("Bxf7+", None),
                ("Kxf7", "Et s'il tente ce dernier piège en se jetant sur f7, prends tout simplement avec ton roi. Compte les pièces : il a donné un fou ET un cavalier pour un seul pion — tu as une pièce et demie d'avance ! Mets ensuite ton roi au calme (...Cf6, ...Te8, ...Rg8) et transforme cet énorme avantage en victoire. 🏆"),
            ]),
            dict(at=6, name="Gambit Evans (4.b4)",
                story="Inventé vers 1827 par William Evans, un capitaine de navire gallois — il l'aurait trouvé en pleine mer, pendant son quart ! Anderssen et Morphy ont gagné des merveilles avec, et Kasparov l'a même ressorti en 1995. Ta réponse : refuser poliment, et son pion b4 devient une faiblesse.",
                moves=[
                ("b4", None),
                ("Bb6", "Le gambit Evans ! Refuse poliment le cadeau : recule, et son pion b4 deviendra une faiblesse.", {
                    "Bxb4": "Prendre, c'est accepter SON gambit : après c3 puis d4, ses pièces sortent à toute vitesse — c'est exactement ce qu'il espère. Refuse poliment : recule le fou en b6 !",
                    "Nxb4": "Le pion b4 est un appât ! Après c3 ton cavalier doit fuir, et il construit son grand centre avec d4 en gagnant du temps. Recule plutôt le fou en b6.",
                }),
                ("a4", None),
                ("a6", "Tu donnes de l'air à ton fou : pas question de le laisser se faire piéger par a5. Et toujours pas touche au pion b4 : c'est un appât !", {
                    "Nxb4": "STOP, b4 est empoisonné ! Après ...Cxb4 ? vient a5 ! et ton fou est coincé : sa case a7 est bouchée par ton propre pion ! Puis c3 chasse ton cavalier et tout s'écroule. Joue d'abord a6 pour ouvrir la sortie a7.",
                }),
                ("a5", None),
                ("Ba7", "À l'abri ! Lui pousse des pions, toi tu vas développer des pièces."),
                ("b5", None),
                ("axb5", "Tu ouvres la colonne a... pour TA tour a8 !"),
                ("Bxb5", None),
                ("Nf6", "Développe en attaquant e4 : qui a gagné du temps dans l'histoire ? Toi. 😎"),
                ("Nc3", None),
                ("O-O", "Roi à l'abri ! Et regarde ta tour a8 : la colonne ouverte est à TOI — cadeau de son gambit."),
                ("O-O", None),
                ("d6", "Solidifie e5 et libère ton fou c8. Bilan de l'Evans : lui a éparpillé ses pions, toi tu as la colonne a et un jeu superbe. 🏆"),
            ]),
            dict(at=16, name="La poussée 9.e5", moves=[
                ("e5", None),
                ("dxc4", "Le coup intermédiaire malin ! Ne bouge SURTOUT pas ton cavalier attaqué : prends d'abord le fou en c4. Tu gagnes une pièce grâce au tempo.", {
                    "Ne4": "Réflexe naturel... mais tu rates un cadeau ! Avant de sauver ton cavalier, prends le fou : ...dxc4 ! Après exf6 Dxf6, tu as une pièce de plus.",
                    "Nd7": "Reculer le cavalier laisse filer l'avantage. Prends d'abord le fou : ...dxc4 ! gagne une pièce contre un pion.",
                    "Ng4": "Pas la peine de fuir : ...dxc4 ! d'abord, et après exf6 Dxf6 tu es une pièce devant.",
                }),
                ("exf6", None),
                ("Qxf6", "Tu reprends : bilan, une PIÈCE pour un pion ! Tu peux ensuite proposer l'échange des dames (après De2+, joue ...De7) et convertir tranquillement. 🎯"),
            ]),
        ],
    ),
    dict(
        id="espagnole-noirs", side="b", emoji="🇪🇸",
        title="Contrer l'Espagnole",
        desc="Face à 3.Fb5 : la recette classique ...a6, ...b5, ...d6 — solide depuis 150 ans !",
        story="L'Espagnole est décrite par le prêtre Ruy López dans un livre de... 1561 ! Et ton 3...a6 porte le nom de Paul Morphy, le génie américain des années 1850 qui écrasait l'Europe entière. C'est l'ouverture la plus analysée de toute l'histoire des échecs.",
        moves=[
            ("e4", None),
            ("e5", "On commence comme d'habitude."),
            ("Nf3", None),
            ("Nc6", "Défense + développement."),
            ("Bb5", None),
            ("a6", "La question au fou (le coup de Morphy) : ou il prend ton cavalier c6 — et tu reprends avec un pion en gardant la PAIRE DE FOUS —, ou il recule. Dans les deux cas tu sais à quoi t'en tenir, et tu commences à bousculer sa belle pièce."),
            ("Ba4", None),
            ("Nf6", "Tu développes en attaquant e4."),
            ("O-O", None),
            ("Be7", "Tranquille : ton roque arrive, tout est protégé."),
            ("Re1", None),
            ("b5", "Maintenant que sa tour e1 garde le pion e4, le pion e5 n'est plus un souci tactique : tu peux enfin repousser le fou pour de bon. (Trop tôt, ...b5 aurait laissé des prises gênantes sur e5.)"),
            ("Bb3", None),
            ("d6", "Tu bétonnes e5 et tu libères ton fou c8."),
            ("c3", None),
            ("O-O", "Roi à l'abri : tu as tout neutralisé, la partie est égale."),
            ("h3", None),
            ("Na5", "Le plan de Tchigorine : ce fou espagnol (en b3) est la pièce la plus dangereuse des Blancs — il braque f7 et toute l'aile roi. Ton cavalier va sur le bord (oui, en a5 !) juste pour le chasser ou l'échanger. Une règle dit « cavalier au bord, cavalier mort »... mais ici il a une MISSION précise : une fois ce fou neutralisé, l'attaque blanche perd ses dents."),
            ("Bc2", None),
            ("c5", "Tu gagnes de l'espace à l'aile dame, et tu prépares à ramener ton cavalier a5 dans le jeu (...Cc6) et ta dame en c7. Tu as tout neutralisé ET tu as un vrai plan : à toi de jouer ! 🚀"),
        ],
        variations=[
            dict(at=6, name="Variante d'échange (4.Fxc6)",
                story="L'arme d'Emanuel Lasker, champion du monde pendant 27 ans (record absolu !), puis de Bobby Fischer qui l'a ressuscitée en 1966. L'idée : abîmer tes pions pour viser la finale. Ta parade : la paire de fous, qui vaut de l'or.",
                moves=[
                ("Bxc6", None),
                ("dxc6", "Reprends avec le pion d : tu ouvres la diagonale de ton fou c8 et tu gardes la paire de fous."),
                ("O-O", None),
                ("f6", "Béton : e5 est solidement défendu, ton mur de pions tient."),
                ("d4", None),
                ("exd4", "Il ouvre le centre ? Prends, tout est calculé."),
                ("Nxd4", None),
                ("c5", "Tu chasses le cavalier en gagnant de l'espace."),
                ("Nb3", None),
                ("Qxd1", "Échange les dames ! Sans dames, son petit avantage s'évapore... et tes deux fous brilleront."),
                ("Rxd1", None),
                ("Bd7", "Développe tranquillement : la paire de fous est ta force pour toute la partie. 🔱"),
            ]),
        ],
    ),
    dict(
        id="ecossaise-noirs", side="b", emoji="🏴",
        title="Contrer l'Écossaise",
        desc="3.d4 tout de suite : réponds 4...Fc5 et harcèle son cavalier d4 — gare à lui s'il prend en c6 !",
        story="Son nom vient d'un match par correspondance Édimbourg contre Londres (1824) : les Écossais l'ont jouée... et gagné le match ! Oubliée pendant un siècle, Garry Kasparov l'a ressuscitée en plein championnat du monde 1990. Depuis, elle est partout.",
        moves=[
            ("e4", None),
            ("e5", "Début habituel."),
            ("Nf3", None),
            ("Nc6", "Défense + développement, comme toujours."),
            ("d4", None),
            ("exd4", "Prends : ne le laisse pas s'installer gratuitement au centre.", {
                "Nxd4": "Pas avec le cavalier ! Après Cxd4 exd4 Dxd4, sa dame trône au centre SANS pouvoir être chassée : ton cavalier c6 n'existe plus. Prends avec le pion.",
            }),
            ("Nxd4", None),
            ("Bc5", "LE coup : tu développes en visant son cavalier d4... et la case f2 derrière !"),
            ("Be3", None),
            ("Qf6", "Encore d4 ! Et ta dame lorgne f2 : il doit rester très prudent."),
            ("c3", None),
            ("Nge7", "Développe SANS bloquer ta dame : e7 est la bonne case ici."),
            ("Bc4", None),
            ("Ne5", "Ton cavalier saute au centre en attaquant son fou : l'initiative est pour toi."),
            ("Be2", None),
            ("Qg6", "Double attaque : le pion g2 ET le pion e4 ! Il doit encore défendre."),
            ("O-O", None),
            ("d6", "Tu consolides ton superbe cavalier e5 (un roc en plein centre). Tes pièces sont plus actives que les siennes — mais n'oublie pas l'essentiel : ton roi est encore au centre ! Le plan : roque d'abord, puis prépare la cassure ...d5 pour ouvrir le jeu pendant que tu es mieux développé. Pièces actives + roi à l'abri = tu prends les commandes. ⚡"),
        ],
        variations=[
            dict(at=8, name="La prise 5.Cxc6", moves=[
                ("Nxc6", None),
                ("Qf6", "Surprise : ne reprends pas tout de suite ! Tu menaces Dxf2 ÉCHEC ET MAT (ton fou c5 soutient f2). Il doit parer."),
                ("Qd2", None),
                ("dxc6", "MAINTENANT tu reprends, avec le pion d : fou c8 libéré, paire de fous, développement de rêve. 🌟"),
            ]),
        ],
    ),
    dict(
        id="gambit-roi-noirs", side="b", emoji="👑",
        title="Contrer le gambit du roi",
        desc="2.f4 : les jeunes attaquants adorent ! Refuse poliment avec 2...Fc5 : son roi ne pourra plus roquer tranquille.",
        story="LE gambit romantique du 19e siècle : la « Partie Immortelle » d'Anderssen (1851) commence par ces coups ! Bobby Fischer, agacé d'avoir perdu contre, a écrit en 1961 un article fameux pour le « réfuter ». Ton refus 2...Fc5 est la façon la plus maligne d'éviter tous ses pièges.",
        moves=[
            ("e4", None),
            ("e5", "Début habituel."),
            ("f4", None),
            ("Bc5", "Le refus malin ! Ton fou vise g1 : impossible pour lui de roquer. Et surtout, ne prends PAS f4 tout de suite.", {
                "exf4": "Accepter, c'est entrer dans SA jungle de pièges, qu'il connaît mieux que toi. Le refus malin ...Fc5 ! vise g1 : plus de roque pour lui — et s'il gobe e5 ?? ...Dh4+ fait exploser sa position.",
            }),
            ("Nf3", None),
            ("d6", "Solidifie e5 tranquillement : son f4 ne sert à rien pour l'instant."),
            ("Nc3", None),
            ("Nf6", "Développe en visant e4."),
            ("Bc4", None),
            ("Nc6", "Encore une pièce : tu joues aux échecs, lui attend son attaque."),
            ("d3", None),
            ("Bg4", "Cloue son cavalier : c'est lui le défenseur de son roi resté au centre."),
            ("h3", None),
            ("Bxf3", "Échange : son roi perd son meilleur garde du corps."),
            ("Qxf3", None),
            ("exf4", "MAINTENANT tu prends f4 : au bon moment, pas avant !"),
            ("Bxf4", None),
            ("Nd4", "Fourchette en vue ! Tu attaques sa dame ET tu vises c2 : l'initiative est pour toi. ⚡ La suite : sa dame doit reculer (encore un temps perdu pour lui), puis tu roques tranquillement. Bilan : tu as la paire de fous et un roi qui sera mieux gardé que le sien — car son coup f4 a laissé des trous devant SON roi. Développe, et joue contre cette faiblesse."),
        ],
        variations=[
            dict(at=4, name="La gourmandise 3.fxe5 ??", moves=[
                ("fxe5", None),
                ("Qh4+", "ÉCHEC ! Voilà pourquoi il ne fallait pas prendre : son roi n'a plus le pion f pour se cacher."),
                ("g3", None),
                ("Qxe4+", "Tu manges e4 avec encore échec : sa partie s'écroule."),
                ("Qe2", None),
                ("Qxh1", "Et tu gagnes la tour h1 ! Une tour entière pour un pion : merci le gambit. 🎁"),
            ]),
        ],
    ),
    dict(
        id="vienne-noirs", side="b", emoji="🎻",
        title="Contrer la Vienne",
        desc="2.Cc3 puis souvent f4 : retiens LE coup magique ...d5 au bon moment !",
        story="Elle est née dans les cafés enfumés de Vienne, la capitale des échecs vers 1850-1900. Les Viennois rêvaient d'un gambit du roi « amélioré »... jusqu'à ce que la parade ...d5 ! (celle que tu apprends) calme leurs ardeurs pour de bon.",
        moves=[
            ("e4", None),
            ("e5", "Comme toujours."),
            ("Nc3", None),
            ("Nf6", "La Vienne ! Développe normalement... et prépare la surprise si f4 arrive."),
            ("f4", None),
            ("d5", "LE coup magique contre le gambit viennois : frappe au centre ! (Surtout pas ...exf4 ?)", {
                "exf4": "C'est LE piège viennois ! Après ...exf4 ? e5 ! ton cavalier f6 doit fuir et son attaque déferle toute seule. Réponds au centre : ...d5 !",
            }),
            ("fxe5", None),
            ("Nxe4", "Ton cavalier s'installe au centre. S'il l'échange avec Cxe4, tu reprends ...dxe4 et tu es très bien."),
            ("Nf3", None),
            ("Be7", "Tranquille : développement d'abord, ton cavalier e4 est costaud."),
            ("d4", None),
            ("O-O", "Roi à l'abri pendant que le sien est encore tout nu au centre."),
            ("Bd3", None),
            ("Nxc3", "Échange au bon moment : tu lui laisses des pions doublés en souvenir."),
            ("bxc3", None),
            ("c5", "Attaque son centre : ses pions abîmés vont souffrir toute la partie. 💪"),
        ],
        variations=[
            dict(at=4, name="Le fou d'abord (3.Fc4)", moves=[
                ("Bc4", None),
                ("Nc6", "Développe simplement : pas de précipitation."),
                ("d3", None),
                ("Bc5", "Ton fou prend sa belle diagonale, comme dans l'Italienne."),
                ("f4", None),
                ("d6", "Le voilà, son f4 ! Réponds solide : e5 est bien gardé, ne lui ouvre rien."),
                ("Nf3", None),
                ("Bg4", "Cloue son cavalier : son attaque est gelée sur place. 🧊"),
            ]),
        ],
    ),
    dict(
        id="anti-danois", side="b", emoji="🇩🇰",
        title="Contrer le gambit danois : 3...d5 !",
        desc="2.d4 et 3.c3 : il offre des pions pour attaquer vite. Qu'il soit simple (4.Cxc3) ou double (4.Fc4), la parade ...d5 règle tout !",
        story="Le gambit danois fut l'arme des attaquants romantiques vers 1900, comme Jacques Mieses : deux pions offerts pour deux fous rasants ! Les parades modernes — dont ton ...d5 ! — l'ont presque fait disparaître des grands tournois... mais pas des tournois jeunes, où il fait toujours des ravages.",
        moves=[
            ("e4", None),
            ("e5", "On commence normalement."),
            ("d4", None),
            ("exd4", "Il offre un pion : prends-le sans peur."),
            ("c3", None),
            ("d5", "LE coup anti-gambit : tu rends le pion tout de suite pour casser son centre AVANT que son attaque commence.", {
                "dxc3": "Tout gober ? C'est possible — tu as un module entier pour ça (🍬) ! — mais SEULEMENT en connaissant la suite par cœur. Ici on apprend la parade simple et solide : ...d5 !",
            }),
            ("exd5", None),
            ("Qxd5", "Ta dame est tranquille ici : son cavalier ne peut pas venir en c3... son propre pion occupe la case !"),
            ("cxd4", None),
            ("Nc6", "Développement avec pression sur d4."),
            ("Nf3", None),
            ("Bg4", "Tu cloues le défenseur de d4 : la pression monte."),
            ("Be2", None),
            ("Bb4+", "Échec intermédiaire : tu gênes son développement."),
            ("Nc3", None),
            ("Bxf3", "Tu élimines le défenseur de d4..."),
            ("Bxf3", None),
            ("Qc4", "Le coup de Capablanca ! Tu attaques d4 et tu proposes l'échange des dames : sans dames, son gambit ne vaut plus rien. 🧊"),
        ],
    ),
    dict(
        id="anti-danois-accepte", side="b", emoji="🍬",
        title="Gambit danois : si tu gobes tout...",
        desc="Tu PEUX accepter les deux pions — mais seulement si tu connais cette suite par cœur : ...d5 puis ...Fb4+ !",
        story="Ta suite ...d5 puis ...Fb4+ porte le nom de Carl Schlechter, le maître viennois qui a frôlé le titre mondial contre Lasker en 1910. Sa recette marche si bien qu'elle a quasiment tué le gambit danois chez les professionnels !",
        moves=[
            ("e4", None),
            ("e5", "Début classique."),
            ("d4", None),
            ("exd4", "Premier pion : merci !"),
            ("c3", None),
            ("dxc3", "Deuxième pion offert... d'accord, mais reste concentré.", {
                "d5": "...d5 est l'AUTRE chemin : le refus malin, ton module 🇩🇰 ! Ici on s'entraîne à tout gober : ...dxc3, en récitant la suite par cœur.",
            }),
            ("Bc4", None),
            ("cxb2", "Troisième ! Tu peux gober SI tu connais la suite. Sinon, rejoue la ligne 3...d5."),
            ("Bxb2", None),
            ("d5", "Le coup d'or : tu rends UN pion pour couper ses deux fous et libérer ton jeu.", {
                "Nf6": "Développer « normalement » ici = DANGER : e5 ! chasse ton cavalier, et ses deux fous + sa dame foncent sur f7 et g7. Le coup d'or : ...d5 ! rends un pion pour couper leurs diagonales.",
            }),
            ("Bxd5", None),
            ("Nf6", "Tu développes en attaquant son fou. Attention, son Fxf7+ arrive... mais c'est prévu !"),
            ("Bxf7+", None),
            ("Kxf7", "Oui, prends ! Il va capturer ta dame... laisse-le faire, le coup suivant est magique."),
            ("Qxd8", None),
            ("Bb4+", "ÉCHEC ! Voilà l'astuce : sa dame est obligée de revenir s'interposer..."),
            ("Qd2", None),
            ("Bxd2+", "...et tu la captures ! Dame contre dame : échange équitable, et son attaque a disparu."),
            ("Nxd2", None),
            ("Re8", "Compte : matériel égal, et surtout PLUS DE DAMES — donc plus aucune attaque possible en face. Tu as transformé son gambit fou en une finale saine et parfaitement égale. Ta tour fixe déjà son pion e4 ; le plan : développe au mieux (ton cavalier rêve du voyage b4 → d3, en plein cœur de son camp), garde la pression et joue cette finale tranquille. Son gambit n'a servi à rien. 🔥"),
        ],
    ),
    dict(
        id="gambit-dame-noirs", side="b", emoji="🗿",
        title="Contrer le Gambit Dame",
        desc="Face à 1.d4 et 2.c4 : le Gambit Dame refusé, solide comme un roc.",
        story="Le Gambit Dame a 500 ans, mais son heure de gloire fut le championnat du monde Capablanca-Alekhine en 1927 : 32 parties sur 34 ont commencé exactement comme ça ! Ton ...e6 est la défense « orthodoxe », le choix des champions du monde depuis un siècle.",
        moves=[
            ("d4", None),
            ("d5", "Tu prends le centre toi aussi : pas peur de 1.d4 !"),
            ("c4", None),
            ("e6", "Tu REFUSES le gambit : ton pion d5 sera toujours protégé.", {
                "dxc4": "Prendre c4, c'est lâcher le centre — et il récupère TOUJOURS son pion (e4 puis Fxc4, ou même Da4+ !). Reste roc : ...e6 protège d5 pour toujours.",
            }),
            ("Nc3", None),
            ("Nf6", "Développement naturel."),
            ("Bg5", None),
            ("Be7", "Tu pares le clouage tranquillement."),
            ("e3", None),
            ("O-O", "Roi en sécurité d'abord."),
            ("Nf3", None),
            ("Nbd7", "Pourquoi pas en c6, sa case naturelle ? Parce que tu veux garder ton pion c LIBRE — pour jouer ...c6 (béton) ou ...c5 (cassure) plus tard. Ce cavalier en d7 soutient son frère f6 et attend son heure."),
            ("Rc1", None),
            ("c6", "Béton ! d5 est protégé 3 fois. Ton plan : ...dxc4 puis ...b5 ou ...c5 au bon moment."),
        ],
        variations=[
            dict(at=4, name="L'échange tout de suite (3.cxd5)", moves=[
                ("cxd5", None),
                ("exd5", "Il échange dès le 3e coup ? Aucune importance : reprends avec le pion e et ton fou c8 respire. C'est la MÊME variante d'échange, un coup plus tôt.", {
                    "Qxd5": "Pas avec la dame ! Après ...Dxd5 ? Cc3 ! la chasse en développant — c'est exactement le tour que TOI tu joues contre la Scandinave ! Reprends avec le pion e : ...exd5 libère ton fou c8.",
                }),
                ("Nc3", None),
                ("Nf6", "Développement naturel : te voilà sur des chemins connus."),
                ("Bg5", None),
                ("Be7", "Tu pares le clouage, comme toujours."),
                ("e3", None),
                ("O-O", "Roi à l'abri d'abord."),
                ("Bd3", None),
                ("c6", "Béton sur d5 : ta structure est ultra-solide."),
                ("Nf3", None),
                ("Nbd7", "Et te voilà dans la position de l'autre échange : UN seul plan à connaître (tour en e8, cavalier vers e4) pour DEUX ordres de coups ! 🐴"),
            ]),
            dict(at=6, name="Variante d'échange (4.cxd5)", moves=[
                ("cxd5", None),
                ("exd5", "Reprends avec le pion e : ton fou c8 est enfin libre de sortir !"),
                ("Bg5", None),
                ("Be7", "Tu pares le clouage, comme dans la ligne principale."),
                ("e3", None),
                ("O-O", "Roi à l'abri d'abord."),
                ("Bd3", None),
                ("c6", "Béton sur d5 : ta structure est ultra-solide."),
                ("Nf3", None),
                ("Nbd7", "Développement terminé. Ton plan : la tour en e8 et le cavalier vers e4 ! 🐴"),
            ]),
        ],
    ),
    dict(
        id="anti-catalane", side="b", emoji="🐱",
        title="Contrer la Catalane",
        desc="1.d4, 2.c4 puis g3 : son fou veut régner sur la grande diagonale. Construis un mur... puis réponds œil pour œil !",
        story="La Catalane est née d'une commande : au tournoi de Barcelone 1929, les organisateurs ont demandé à Tartakover d'inventer une ouverture en l'honneur de la Catalogne ! Aujourd'hui c'est l'arme chouchoute des champions positionnels, comme Kramnik.",
        moves=[
            ("d4", None),
            ("d5", "Le centre, comme d'habitude."),
            ("c4", None),
            ("e6", "Tu protèges d5 : même début que contre le Gambit Dame."),
            ("Nf3", None),
            ("Nf6", "Développement naturel."),
            ("g3", None),
            ("Be7", "Voilà la Catalane ! Pas de panique : ne prends pas c4, développe-toi tranquillement.", {
                "dxc4": "Contre la Catalane, prendre c4 est risqué : son fou arrive en g2 PILE sur la diagonale pour récupérer le pion avec intérêts (Ce5, Da4+...). Continue ton développement béton.",
            }),
            ("Bg2", None),
            ("O-O", "Roi à l'abri pendant qu'il prépare son grand fou."),
            ("O-O", None),
            ("Nbd7", "Ce cavalier prépare le plan ...c6 puis ...b6."),
            ("Qc2", None),
            ("c6", "Le mur ! Son fou g2 mord dans du béton : d5 est verrouillé."),
            ("b3", None),
            ("b6", "Tu prépares la réponse du berger à la bergère..."),
            ("Bb2", None),
            ("Bb7", "Œil pour œil : TON fou prend la même grande diagonale que le sien ! Plan : ...c5 ou ...Ce4 au bon moment. 😼"),
        ],
        variations=[
            dict(at=8, name="L'échange 5.cxd5", moves=[
                ("cxd5", None),
                ("exd5", "Reprends avec le pion e : ton fou c8 est enfin libre !"),
                ("Bg2", None),
                ("O-O", "Roi en sécurité d'abord, toujours."),
                ("O-O", None),
                ("c6", "Béton sur d5 : son fou g2 ne mange que du granit."),
                ("Nc3", None),
                ("Nbd7", "Développe : ce cavalier visera e4 ou b6 plus tard."),
                ("Qc2", None),
                ("Re8", "Ta tour prend la colonne ouverte : position égale et facile à jouer. 💪"),
            ]),
        ],
    ),
    dict(
        id="anti-londres", side="b", emoji="🎡",
        title="Contrer le système de Londres",
        desc="1.d4 et 2.Ff4 : TRÈS joué chez les jeunes. Attaque b2, le talon d'Achille de la Londres !",
        story="Son nom vient du grand tournoi de Londres 1922, où plusieurs maîtres l'ont adoptée. Longtemps surnommée « l'ouverture des paresseux » (toujours le même schéma quoi qu'il arrive !), elle a explosé de popularité — même Carlsen s'y est mis. Raison de plus pour connaître sa faiblesse : b2 !",
        moves=[
            ("d4", None),
            ("d5", "Tu prends le centre."),
            ("Bf4", None),
            ("c5", "Tu attaques d4 tout de suite : pas question de le laisser s'installer."),
            ("e3", None),
            ("Nc6", "Encore de la pression sur d4."),
            ("c3", None),
            ("Qb6", "LE coup clé : le fou f4 est parti... b2 n'est plus défendu !"),
            ("Qb3", None),
            ("c4", "Tu repousses sa dame en gagnant de l'espace.", {
                "Qxb3": "N'échange pas ! Après axb3, SA tour a1 s'ouvre une autoroute sur la colonne a. Pousse ...c4 ! et sa dame doit encore reculer, toute seule.",
            }),
            ("Qc2", None),
            ("Nf6", "Développement tranquille. Ton pari est déjà gagné : sa dame a été promenée de b3 à c2, loin du jeu, pendant que tu tiens le centre et l'espace. Pas de coup risqué — tu finis ton développement, la position est saine. 🎡"),
        ],
        variations=[
            dict(at=10, name="L'échange 6.Dxb6", moves=[
                ("Qxb6", None),
                ("axb6", "Reprends avec le pion a — et dis merci : ta tour a8 obtient une colonne demi-ouverte braquée sur a2, sans bouger ! Et tes pions b doublés ne sont pas faibles... ce sont des béliers."),
                ("Nf3", None),
                ("Bf5", "La règle d'or : le fou sort AVANT ...e6, sinon il reste muré derrière ses pions."),
                ("Nbd2", None),
                ("b5", "Le rouleau compresseur se met en marche : le pion doublé prépare ...b4 !"),
                ("Be2", None),
                ("b4", "La percée ! Tu frappes c3 et tu ouvres les lignes côté dame, là où TA tour et TON espace dominent. Sans les dames, il n'a aucune attaque en face : tu joues tout seul. 🚜"),
            ]),
            dict(at=4, name="La prise 3.dxc5", moves=[
                ("dxc5", None),
                ("e6", "Il a gobé le pion ? Pas de panique : ton FOU va le reprendre. Et s'il essaie de le garder avec b4 ?, joue ...a5 ! et sa chaîne s'écroule."),
                ("e3", None),
                ("Bxc5", "Tu reprends en DÉVELOPPANT : le fou est superbe ici. Et compte le centre : son pion d4 a disparu, ton pion d5 règne tout seul !"),
                ("Nf3", None),
                ("Nc6", "Développement naturel : tu as un temps d'avance et le centre."),
                ("Bd3", None),
                ("Nf6", "Trois pièces dehors, le centre pour toi... sa prise dxc5 t'a rendu service ! Roque, puis prépare ...e5 pour tout ouvrir. 😏"),
            ]),
        ],
    ),
    dict(
        id="anglaise-noirs", side="b", emoji="🇬🇧",
        title="Contrer l'Anglaise",
        desc="1.c4 : ne te laisse pas dérouter. Joue ...e5 : c'est une Sicilienne à l'envers, et le centre est pour toi !",
        story="L'Anglaise porte le nom de Howard Staunton, le champion anglais des années 1840 — celui qui a donné son nom à la forme officielle des pièces ! Bobby Fischer a créé la surprise en la jouant contre Spassky en 1972, au championnat du monde le plus célèbre de l'histoire.",
        moves=[
            ("c4", None),
            ("e5", "Contre l'Anglaise, joue ce que tu connais : le centre ! Tu joues une Sicilienne... à l'envers."),
            ("Nc3", None),
            ("Nf6", "Développement naturel."),
            ("Nf3", None),
            ("Nc6", "Encore une pièce vers le centre."),
            ("g3", None),
            ("d5", "La poussée libératrice : c'est TOI qui joues au centre, pas lui."),
            ("cxd5", None),
            ("Nxd5", "Reprends avec le cavalier : il trône au milieu."),
            ("Bg2", None),
            ("Nb6", "Petit recul malin : tu sors de la diagonale de son fou g2, qui tape dans le vide."),
            ("O-O", None),
            ("Be7", "Développe tranquillement : ta position est confortable."),
            ("d3", None),
            ("O-O", "Roi à l'abri : tu as fait jeu égal au centre (une Sicilienne à l'envers, version solide). Ton plan tout simple : sortir ta dernière pièce avec ...Fe6, puis grignoter à l'aile dame avec ...a5. Position saine, partie qui commence bien. ✨"),
        ],
    ),
]


def process_moves(board, moves, ctx):
    """Valide une séquence de coups SAN sur `board` et renvoie les dicts pour le JSON.
    Une entrée peut avoir un 3e élément {san_erreur: explication} : les pièges
    typiques tentés À LA PLACE de ce coup, expliqués au moment de l'erreur."""
    out = []
    for entry in moves:
        san, comment = entry[0], entry[1]
        traps_in = entry[2] if len(entry) > 2 else {}
        try:
            move = board.parse_san(san)
        except ValueError as e:
            raise SystemExit(f"[{ctx}] coup illégal {san}: {e}")
        traps = []
        for tsan, ttext in traps_in.items():
            try:
                tmove = board.parse_san(tsan)
            except ValueError as e:
                raise SystemExit(f"[{ctx}] piège illégal {tsan}: {e}")
            assert tmove != move, f"[{ctx}] le piège {tsan} est identique au bon coup"
            traps.append(dict(
                san=tsan,
                from_=chess.square_name(tmove.from_square),
                to=chess.square_name(tmove.to_square),
                text=ttext,
            ))
        if board.is_en_passant(move):
            raise SystemExit(f"[{ctx}] {san} est une prise en passant (non gérée)")
        castle = None
        if board.is_kingside_castling(move):
            castle = "K"
        elif board.is_queenside_castling(move):
            castle = "Q"
        color = "w" if board.turn == chess.WHITE else "b"
        d = dict(
            san=san,
            from_=chess.square_name(move.from_square),
            to=chess.square_name(move.to_square),
            castle=castle,
            color=color,
            comment=comment,
        )
        if traps:
            d["traps"] = traps
        out.append(d)
        board.push(move)
        if san.endswith("#"):
            assert board.is_checkmate(), f"[{ctx}] {san} n'est pas mat !"
    return out


# Ordre d'affichage (du plus classique au plus original, par couleur) et niveau de chaque module
ORDER_LEVELS = {
    # ------- Blancs -------
    "anglaise-chouchou":    "avance",
    "italienne-blancs":     "debutant",
    "anti-scandinave":      "debutant",
    "anti-francaise":       "debutant",
    "anti-caro":            "inter",
    "anti-sicilienne":      "inter",
    "anti-pirc":            "inter",
    "piege-legal":          "debutant",
    "fried-liver":          "avance",
    "morra":                "avance",
    # ------- Noirs -------
    "anti-berger":          "debutant",
    "italienne-noirs":      "debutant",
    "espagnole-noirs":      "inter",
    "ecossaise-noirs":      "inter",
    "gambit-dame-noirs":    "inter",
    "anti-londres":         "inter",
    "vienne-noirs":         "inter",
    "gambit-roi-noirs":     "inter",
    "anti-danois":          "inter",
    "anti-danois-accepte":  "avance",
    "anglaise-noirs":       "avance",
    "anti-catalane":        "avance",
}


def main():
    ids = [l["id"] for l in LINES]
    assert sorted(ids) == sorted(ORDER_LEVELS), \
        f"ORDER_LEVELS désynchronisé : {set(ids) ^ set(ORDER_LEVELS)}"
    rank = list(ORDER_LEVELS)
    out = []
    for line in sorted(LINES, key=lambda l: rank.index(l["id"])):
        board = chess.Board()
        moves_out = process_moves(board, line["moves"], line["id"])
        # le dernier coup doit être joué par l'enfant (= la couleur de la ligne)
        assert moves_out[-1]["color"] == line["side"], f"[{line['id']}] dernier coup pas au trait de l'enfant"
        vars_out = []
        for var in line.get("variations", []):
            at = var["at"]
            # le point de divergence doit être un coup de l'adversaire, différent du coup principal
            assert moves_out[at]["color"] != line["side"], f"[{line['id']}/{var['name']}] 'at' ne pointe pas un coup adverse"
            assert var["moves"][0][0] != moves_out[at]["san"], f"[{line['id']}/{var['name']}] même coup que la ligne principale"
            vboard = chess.Board()
            for entry in line["moves"][:at]:
                vboard.push_san(entry[0])
            vmoves = process_moves(vboard, var["moves"], f"{line['id']}/{var['name']}")
            assert vmoves[0]["color"] != line["side"], f"[{line['id']}/{var['name']}] doit commencer par un coup adverse"
            assert vmoves[-1]["color"] == line["side"], f"[{line['id']}/{var['name']}] dernier coup pas au trait de l'enfant"
            vars_out.append(dict(at=at, name=var["name"], story=var.get("story"), moves=vmoves))
        out.append(dict(
            id=line["id"], side=line["side"], emoji=line["emoji"], level=ORDER_LEVELS[line["id"]],
            title=line["title"], desc=line["desc"], story=line.get("story"),
            moves=moves_out, variations=vars_out,
        ))
        print(f"OK  {line['id']:24s} {len(moves_out):2d} demi-coups, {len(vars_out)} variante(s)")
    with open("lines.json", "w") as f:
        json.dump(out, f, ensure_ascii=False)
    print(f"\n{len(out)} lignes validées -> lines.json")


if __name__ == "__main__":
    main()
